#!/usr/bin/env python3
'''
Generate main-nodeps-standalone.py: the Linux side as ONE file with NO
dependencies. That is the file to paste over the App's main.py.

It inlines:
    neon_ai.py    the two AI models
    shoal.py      the authoritative shared shoal
    dashboard.py  the App Lab game dashboard

into main-nodeps.py, which already implements the WebSocket server on raw
sockets rather than the `websockets` package.

Re-run whenever any of those three change, or the standalone copy silently
drifts out of date:

    python3 build-standalone.py
'''

import re
import sys

HEADER = '''# Neon-Net - Linux side, SINGLE FILE, NO DEPENDENCIES
# ----------------------------------------------------
# GENERATED by build-standalone.py. Do not edit directly: edit main-nodeps.py,
# neon_ai.py, shoal.py or dashboard.py and regenerate, or it will be lost.
#
# Paste this whole file over the App\'s main.py. Nothing to install, no second
# file needed. It contains:
#   - the two AI models (trajectory prediction, adaptive difficulty)
#   - the App Lab game dashboard on port 8080
#   - a WebSocket server on port 8765, raw sockets, no packages
#   - per player multiplayer sessions
#   - the Bridge polling loop for the MCU

'''


def inline(text, marker, source, start_pattern, label):
    m = re.search(start_pattern, source, re.M)
    if not m:
        print('could not find the start of %s' % label, file=sys.stderr)
        return None
    if marker not in text:
        print('could not find the %s import' % label, file=sys.stderr)
        return None
    body = source[m.start():].rstrip()
    return text.replace(
        marker,
        '# ============ %s, inlined ============\n\n' % label
        + body
        + '\n\n# ============ end of %s ============\n' % label
    )


def main():
    out = HEADER + open('main-nodeps.py').read()

    out = inline(out,
                 'from neon_ai import AdaptiveDifficulty, TrajectoryPredictor',
                 open('neon_ai.py').read(),
                 r'^from collections import deque',
                 'neon_ai.py')
    if out is None:
        return 1

    out = inline(out,
                 'from shoal import Shoal',
                 open('shoal.py').read(),
                 r'^import math$',
                 'shoal.py')
    if out is None:
        return 1

    out = inline(out,
                 'from dashboard import start_dashboard',
                 open('dashboard.py').read(),
                 r'^import json$',
                 'dashboard.py')
    if out is None:
        return 1

    open('main-nodeps-standalone.py', 'w').write(out)
    print('wrote main-nodeps-standalone.py (%d lines)' % out.count('\n'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
