#!/usr/bin/env python3
'''
Generate main-standalone.py: main.py with neon_ai.py inlined.

Arduino App Lab may or may not let you add a second Python file alongside
main.py. If it does, use main.py and neon_ai.py as they are. If it does not,
paste main-standalone.py instead and everything works from one file.

Re-run this whenever neon_ai.py or main.py changes, or the standalone copy
silently drifts out of date:

    python3 build-standalone.py
'''

import re
import sys

HEADER = '''# Neon-Net - Linux side, SINGLE FILE build
# ----------------------------------------
# GENERATED by build-standalone.py. Do not edit this file directly: edit
# main.py or neon_ai.py and regenerate, or your change will be lost.
#
# This is main.py with neon_ai.py inlined, for the case where Arduino App Lab
# will not take a second Python file. Behaviour is identical.

'''


def main():
    ai = open('neon_ai.py').read()
    dash = open('dashboard.py').read()
    app = open('main.py').read()

    # Drop the leading comment block from neon_ai so the two headers do not
    # stack up. Keep everything from the first real statement onwards.
    m = re.search(r'^from collections import deque', ai, re.M)
    if not m:
        print('could not find the start of neon_ai.py code', file=sys.stderr)
        return 1
    ai_body = ai[m.start():]

    # Replace the import with the inlined module.
    marker = 'from neon_ai import AdaptiveDifficulty, TrajectoryPredictor'
    if marker not in app:
        print('could not find the neon_ai import in main.py', file=sys.stderr)
        return 1

    inlined = (
        '# ===================== neon_ai.py, inlined =====================\n\n'
        + ai_body.rstrip()
        + '\n\n# =================== end of inlined neon_ai ===================\n'
    )
    out = HEADER + app.replace(marker, inlined)

    # dashboard.py too, or the 'single file' build still needs a second file.
    d = re.search(r'^import json$', dash, re.M)
    if not d:
        print('could not find the start of dashboard.py code', file=sys.stderr)
        return 1
    dash_body = dash[d.start():]
    dash_marker = 'from dashboard import start_dashboard'
    if dash_marker not in out:
        print('could not find the dashboard import in main.py', file=sys.stderr)
        return 1
    out = out.replace(
        dash_marker,
        '# ==================== dashboard.py, inlined ====================\n\n'
        + dash_body.rstrip()
        + '\n\n# ================== end of inlined dashboard ==================\n'
    )

    open('main-standalone.py', 'w').write(out)
    print('wrote main-standalone.py (%d lines)' % out.count('\n'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
