# Neon-Net - Linux side, SINGLE FILE, NO DEPENDENCIES
# ----------------------------------------------------
# GENERATED by build-standalone.py. Do not edit directly: edit main-nodeps.py,
# neon_ai.py or dashboard.py and regenerate, or your change will be lost.
#
# Paste this whole file over the App's main.py. Nothing to install, no second
# file needed. It contains:
#   - the two AI models (trajectory prediction, adaptive difficulty)
#   - the App Lab game dashboard on port 8080
#   - a WebSocket server on port 8765, raw sockets, no packages
#   - per player multiplayer sessions
#   - the Bridge polling loop for the MCU

# Neon-Net - Linux side, NO DEPENDENCIES build
# ---------------------------------------------
# Identical behaviour to main.py, but the WebSocket server is raw sockets from
# the standard library instead of the `websockets` package. Use this when
# App Lab will not install dependencies into the app container.
#
# The frame layer here is the same code proven end to end in mock-net.py:
# handshake, masked inbound frames, unmasked outbound frames.
#
# Nothing to install. Nothing to fail on the day.

import json
import threading
import time
import socket
import struct
import base64
import hashlib

from arduino.app_utils import *

# ============ neon_ai.py, inlined ============

from collections import deque

# ---------------------------------------------------------------- prediction

DEFAULT_HORIZON_MS = 100.0


class Prediction:
    '''A forecast that a swing will peak shortly.'''

    def __init__(self, eta_ms, predicted_peak, confidence):
        self.eta_ms = eta_ms
        self.predicted_peak = predicted_peak
        self.confidence = confidence

    def as_dict(self):
        return {
            'etaMs': round(self.eta_ms, 1),
            'predictedPeak': round(self.predicted_peak, 2),
            'confidence': round(self.confidence, 2)
        }

    def __repr__(self):
        return ('Prediction(eta_ms=%.1f, peak=%.2f, conf=%.2f)'
                % (self.eta_ms, self.predicted_peak, self.confidence))


class TrajectoryPredictor:
    '''
    Watches acceleration magnitude and extrapolates forward to find the peak.

    The model fits a parabola through three smoothed points and solves for its
    vertex, which is the peak of the swing. If that vertex lands inside the
    horizon, the swing is announced early along with the peak value it is
    heading for.

    A parabola rather than plain Newtonian extrapolation on purpose: a swing
    decelerates harder the closer it gets to its peak, so projecting the
    current slope forward at constant acceleration lands the peak roughly twice
    as far ahead as it really is. Fitting the curve through three points picks
    the turning point up directly.

    One prediction per swing. It re-arms once the motion has died back down,
    so a single swing cannot fire a burst of forecasts.
    '''

    # Calibrated against the net as actually built, not a bare breadboard.
    # Mounting the electronics on a handle tripled the walking figure:
    #
    #                  bare board      mounted on the net
    #   walking        0.65 to 1.08    2.0 to 3.0
    #   a real swing   peaks at 5.5    above 4.0
    #
    # The old arm threshold of 1.6 g sat well below walking, so the predictor
    # armed on every footfall. 3.4 clears both steady walking and a brisk
    # jostling carry, which peaks nearer 3.2. Re-arm at 2.4 so it resets
    # between swings without needing the net to come fully to rest.
    #
    # NOTE: measured WITHOUT the power bank fitted. Adding that mass will move
    # the walking figure again, so re-measure once the net is complete.
    def __init__(self,
                 horizon_ms=DEFAULT_HORIZON_MS,
                 arm_threshold_g=3.4,
                 rearm_threshold_g=2.4,
                 min_slope=8.0,
                 smoothing=3):
        self.horizon_ms = float(horizon_ms)
        self.arm_threshold_g = float(arm_threshold_g)
        self.rearm_threshold_g = float(rearm_threshold_g)
        self.min_slope = float(min_slope)
        self.smoothing = max(1, int(smoothing))

        self._samples = deque(maxlen=16)   # (t_seconds, magnitude_g)
        self._armed = True
        self.last_prediction = None

    def reset(self):
        self._samples.clear()
        self._armed = True
        self.last_prediction = None

    def _smoothed(self, index_from_end):
        '''Mean of the last `smoothing` samples ending at the given offset.'''
        end = len(self._samples) - index_from_end
        start = max(0, end - self.smoothing)
        window = list(self._samples)[start:end]
        if not window:
            return None
        t = sum(s[0] for s in window) / len(window)
        mag = sum(s[1] for s in window) / len(window)
        return t, mag

    def update(self, t_seconds, magnitude_g):
        '''
        Feed one IMU sample. Returns a Prediction the moment a peak is
        forecast inside the horizon, otherwise None.
        '''
        self._samples.append((float(t_seconds), float(magnitude_g)))

        # Re-arm once the net has settled, ready for the next swing.
        if not self._armed and magnitude_g < self.rearm_threshold_g:
            self._armed = True
            return None

        if not self._armed:
            return None
        if magnitude_g < self.arm_threshold_g:
            return None
        if len(self._samples) < self.smoothing * 3:
            return None

        # Three smoothed points, evenly spaced back through the buffer.
        p2 = self._smoothed(0)
        p1 = self._smoothed(self.smoothing)
        p0 = self._smoothed(self.smoothing * 2)
        if p0 is None or p1 is None or p2 is None:
            return None

        t0, m0 = p0
        t1, m1 = p1
        t2, m2 = p2

        dt1 = t2 - t1
        dt0 = t1 - t0
        if dt1 <= 1e-6 or dt0 <= 1e-6:
            return None

        # Divided differences give the parabola through the three points.
        f01 = (m1 - m0) / dt0
        f12 = (m2 - m1) / dt1
        curvature = (f12 - f01) / (t2 - t0)      # the quadratic coefficient

        # Must be rising, and curving over. That combination has a peak ahead.
        v_now = f12
        if v_now <= self.min_slope or curvature >= -1e-9:
            return None

        # Vertex of the parabola, in Newton form.
        t_peak = 0.5 * (t0 + t1) - f01 / (2.0 * curvature)

        eta_s = t_peak - t2
        eta_ms = eta_s * 1000.0
        if eta_ms <= 0 or eta_ms > self.horizon_ms:
            return None

        predicted_peak = (m0
                          + f01 * (t_peak - t0)
                          + curvature * (t_peak - t0) * (t_peak - t1))

        # Confidence falls off as the forecast reaches further ahead, and rises
        # with how decisively the swing is accelerating.
        reach = 1.0 - (eta_ms / self.horizon_ms)
        vigour = min(1.0, v_now / (self.min_slope * 4.0))
        confidence = max(0.0, min(1.0, 0.45 * reach + 0.55 * vigour))

        self._armed = False
        self.last_prediction = Prediction(eta_ms, predicted_peak, confidence)
        return self.last_prediction


# ---------------------------------------------------------------- difficulty

class AdaptiveDifficulty:
    '''
    Keeps the player near a target catch rate.

    Every swing produces a hit or a miss. Over a sliding window the ratio is
    compared against target_ratio, and a single difficulty value between 0 and
    1 moves to close the gap. Too easy and it climbs, too hard and it drops.

    The Lens receives derived parameters rather than the raw number, so all the
    balancing lives here on the board and the Lens simply obeys.
    '''

    def __init__(self,
                 window=10,
                 target_ratio=0.55,
                 dead_band=0.12,
                 step=0.1,
                 start=0.35,
                 min_samples=4):
        self.window = int(window)
        self.target_ratio = float(target_ratio)
        self.dead_band = float(dead_band)
        self.step = float(step)
        self.min_samples = int(min_samples)

        self._outcomes = deque(maxlen=self.window)
        self._difficulty = max(0.0, min(1.0, float(start)))
        self.swings = 0
        self.hits = 0

    # -- inputs --

    def record_result(self, hit):
        '''Record the outcome of one swing, then re-balance.'''
        self._outcomes.append(bool(hit))
        self.swings += 1
        if hit:
            self.hits += 1
        self._rebalance()

    def _rebalance(self):
        if len(self._outcomes) < self.min_samples:
            return
        ratio = self.catch_ratio()
        if ratio > self.target_ratio + self.dead_band:
            self._difficulty = min(1.0, self._difficulty + self.step)
        elif ratio < self.target_ratio - self.dead_band:
            self._difficulty = max(0.0, self._difficulty - self.step)

    # -- outputs --

    def catch_ratio(self):
        if not self._outcomes:
            return 0.0
        return sum(1 for o in self._outcomes if o) / float(len(self._outcomes))

    def level(self):
        return self._difficulty

    def params(self):
        '''
        The message the Lens acts on. Everything is a multiplier so the Lens
        keeps its own tuned baselines and simply scales them.
        '''
        d = self._difficulty
        return {
            'type': 'difficulty',
            'level': round(d, 3),
            'catchRatio': round(self.catch_ratio(), 3),
            'speedMult': round(1.0 + d * 0.8, 3),      # drift and flee speed
            'evasionMult': round(1.0 + d * 1.2, 3),    # how far they dodge
            'alertMult': round(1.0 + d * 0.9, 3),      # how early they notice
            'cloaking': d > 0.65,                      # rare ones fade out
            'skittishBias': round(min(0.8, 0.35 + d * 0.45), 3)
        }

# ============ end of neon_ai.py ============

# ============ dashboard.py, inlined ============

import json
import socket
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer

DASHBOARD_PORT = 8080

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Neon-Net Control</title>
<style>
 /* A single, deliberately dark instrument panel. It is filmed beside gameplay
    footage shot in a dim room, so it commits to one look rather than tracking
    the viewer's theme. Every colour is painted explicitly. */
 :root{
   --abyss:#06101a;      /* page ground */
   --panel:#0d1a26;      /* card ground */
   --panel-2:#112331;    /* nested wells */
   --line:#1d3040;
   --ink:#dcecf2;
   --dim:#6b8896;        /* slate with a cyan bias, not a neutral grey */
   --cyan:#2ff0e0;
   --violet:#8a7dff;
   --gold:#ffc247;
   --coral:#ff6b7a;
 }
 *{box-sizing:border-box}
 html{-webkit-text-size-adjust:100%}
 body{
   margin:0;background:var(--abyss);color:var(--ink);
   font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;
   font-size:15px;line-height:1.55;
 }
 .mono{font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace}
 .num{font-variant-numeric:tabular-nums;
   font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace}

 .wrap{max-width:1060px;margin:0 auto;padding:26px 18px 64px;
   display:flex;flex-direction:column;gap:26px}

 /* ---- header ---- */
 header{display:flex;justify-content:space-between;align-items:flex-start;
   flex-wrap:wrap;gap:14px;border-bottom:1px solid var(--line);
   padding-bottom:16px}
 h1{margin:0;font-size:19px;letter-spacing:.18em;text-transform:uppercase;
   font-weight:600}
 header p{margin:6px 0 0;color:var(--dim);font-size:13px;max-width:56ch}
 .live{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--dim);
   letter-spacing:.1em;text-transform:uppercase;white-space:nowrap}
 .dot{width:8px;height:8px;border-radius:50%;background:var(--cyan);
   box-shadow:0 0 10px var(--cyan);animation:p 1.6s infinite}
 .dot.off{background:#4a5c67;box-shadow:none;animation:none}
 @keyframes p{0%,100%{opacity:1}50%{opacity:.25}}
 @media (prefers-reduced-motion:reduce){.dot{animation:none}}

 /* ---- shared bits ---- */
 .k{font-size:10.5px;letter-spacing:.15em;text-transform:uppercase;
   color:var(--dim)}
 section>h2{margin:0 0 4px;font-size:12px;letter-spacing:.16em;
   text-transform:uppercase;color:var(--ink);font-weight:600}
 section>p.lead{margin:0 0 14px;color:var(--dim);font-size:13px;max-width:64ch}

 /* ---- player cards: the hero of the page ---- */
 .players{display:grid;gap:14px;
   grid-template-columns:repeat(auto-fit,minmax(300px,1fr))}
 .player{background:var(--panel);border:1px solid var(--line);border-radius:6px;
   padding:18px;display:flex;flex-direction:column;gap:16px}
 .player.lead-player{border-color:#2f4a52;box-shadow:inset 3px 0 0 var(--gold)}
 .phead{display:flex;justify-content:space-between;align-items:flex-start;
   gap:10px}
 .pname{font-size:17px;font-weight:600;letter-spacing:.03em}
 .paddr{font-size:11.5px;color:var(--dim);margin-top:2px}
 .chip{font-size:10.5px;letter-spacing:.12em;text-transform:uppercase;
   padding:3px 8px;border:1px solid currentColor;border-radius:99px;
   white-space:nowrap}
 .calm{color:var(--cyan)}
 .curious{color:var(--violet)}
 .spooked{color:var(--gold)}
 .crown{color:var(--gold);font-size:10.5px;letter-spacing:.14em;
   text-transform:uppercase;margin-top:6px;display:block}

 .pstats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}
 .pstats .v{font-size:27px;margin-top:3px;line-height:1.15}
 .pstats small{display:block;font-size:11.5px;color:var(--dim);
   font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;margin-top:2px}

 .diff{background:var(--panel-2);border-radius:4px;padding:13px 14px}
 .dhead{display:flex;justify-content:space-between;align-items:baseline;gap:8px}
 .dband{font-size:13px}
 .bar{height:7px;background:#0a1620;border-radius:4px;overflow:hidden;
   margin-top:9px}
 .bar i{display:block;height:100%;border-radius:4px;transition:width .45s ease}
 .note{margin:10px 0 0;font-size:12.5px;color:var(--dim);line-height:1.5}

 .empty{background:var(--panel);border:1px dashed var(--line);border-radius:6px;
   padding:26px 20px;color:var(--dim);font-size:13.5px}
 .empty strong{color:var(--ink);display:block;margin-bottom:6px;
   font-weight:600;font-size:14px}

 /* ---- the two AI models ---- */
 .models{display:grid;gap:14px;
   grid-template-columns:repeat(auto-fit,minmax(300px,1fr))}
 .model{background:var(--panel);border:1px solid var(--line);border-radius:6px;
   padding:18px;display:flex;flex-direction:column;gap:14px}
 .mname{font-size:14px;font-weight:600;letter-spacing:.03em}
 .mname span{display:block;font-size:10.5px;letter-spacing:.14em;
   text-transform:uppercase;color:var(--cyan);margin-bottom:5px;font-weight:400}
 .model.b .mname span{color:var(--violet)}
 .mdesc{margin:0;font-size:12.5px;color:var(--dim);line-height:1.55}
 .mstats{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;
   border-top:1px solid var(--line);padding-top:13px;margin-top:auto}
 .mstats .v{font-size:22px;margin-top:3px}

 /* ---- footer strip ---- */
 .strip{display:flex;flex-wrap:wrap;gap:22px 34px;border-top:1px solid var(--line);
   padding-top:16px;color:var(--dim);font-size:12.5px}
 .strip b{color:var(--ink);font-weight:600}
</style></head><body>
<div class="wrap">

 <header>
   <div>
     <h1>Neon-Net Control</h1>
     <p>Running on the Arduino UNO Q. It hosts the game, keeps one session per
        player, and re-tunes the jellyfish for each of them independently.</p>
   </div>
   <div class="live"><span class="dot" id="dot"></span><span id="status">connecting</span></div>
 </header>

 <section>
   <h2>Players in this world</h2>
   <p class="lead">Every pair of Spectacles that connects gets its own session
      and its own difficulty AI, so two people of different skill can share the
      same room and each get a fair game.</p>
   <div class="players" id="players"></div>
 </section>

 <section>
   <h2>The AI running on the board</h2>
   <p class="lead">Both models run on the UNO Q's Qualcomm Linux side. Nothing
      is sent to the cloud.</p>
   <div class="models">
     <div class="model a">
       <div class="mname"><span>Model 1</span>Predictive Trajectory AI</div>
       <p class="mdesc">Reads the net's motion 200 times a second and works out
          when the swing will peak, roughly a tenth of a second before it does.
          The glasses are told a catch is coming while the net is still moving,
          which is what hides the wireless delay.</p>
       <div class="mstats">
         <div><div class="k">Swings forecast</div><div class="v num" id="preds">0</div></div>
         <div><div class="k">Warning given</div><div class="v num" id="eta">--</div></div>
       </div>
     </div>
     <div class="model b">
       <div class="mname"><span>Model 2</span>Adaptive Difficulty AI</div>
       <p class="mdesc">Watches how often each player actually catches something
          over their last ten swings and moves their difficulty to keep them near
          a 55 per cent catch rate. Too easy and the shoal speeds up and starts
          cloaking; too hard and it eases off.</p>
       <div class="mstats">
         <div><div class="k">Players tuned</div><div class="v num" id="tuned">0</div></div>
         <div><div class="k">Forecast confidence</div><div class="v num" id="conf">--</div></div>
       </div>
     </div>
   </div>
 </section>

 <div class="strip">
   <span><b id="swings">0</b> swings taken</span>
   <span><b id="catches">0</b> jellyfish caught</span>
   <span>running for <b id="up">--</b></span>
   <span>refreshing twice a second</span>
 </div>

</div>
<script>
function pct(x){ return Math.round((x||0)*100) + '%'; }
function esc(s){ return String(s==null?'':s).replace(/[&<>"]/g,
  function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]; }); }

// Plain words for a number between 0 and 1, so nobody has to know what 0.45
// means. The bands match what the Lens actually does at each level.
function band(d){
  if(d < 0.25) return {word:'Gentle',   col:'var(--cyan)'};
  if(d < 0.45) return {word:'Easy',     col:'var(--cyan)'};
  if(d < 0.65) return {word:'Balanced', col:'var(--violet)'};
  if(d < 0.85) return {word:'Hard',     col:'var(--gold)'};
  return           {word:'Brutal',   col:'var(--coral)'};
}

// What the difficulty AI last decided, said out loud. The thresholds are the
// model's real target and dead band, sent with the state rather than guessed.
function note(p){
  var target = (p.target_ratio == null) ? 0.55 : p.target_ratio;
  var dead   = (p.dead_band == null) ? 0.12 : p.dead_band;
  if(p.swings < 4)
    return 'Watching the first few swings before it changes anything.';
  if(p.catch_ratio > target + dead)
    return 'Catching more than ' + pct(target) + ' of swings, so the shoal was '
         + 'sped up and made harder to sneak up on.';
  if(p.catch_ratio < target - dead)
    return 'Catching less than ' + pct(target) + ' of swings, so the shoal was '
         + 'slowed down and made less jumpy.';
  return 'Catch rate is inside the ' + pct(target - dead) + ' to '
       + pct(target + dead) + ' band the AI aims for, so difficulty is '
       + 'holding steady.';
}

function moodChip(m){
  var words = {calm:'Shoal calm', curious:'Shoal curious',
               spooked:'Shoal spooked'};
  var cls = (m === 'curious' || m === 'spooked') ? m : 'calm';
  return '<span class="chip ' + cls + '">' + (words[cls]) + '</span>';
}

function playerCard(p, leading, many){
  var d = p.difficulty || 0, b = band(d);
  return '<article class="player' + (leading ? ' lead-player' : '') + '">'
    + '<div class="phead"><div>'
    +   '<div class="pname">Player ' + esc(p.id) + '</div>'
    +   '<div class="paddr mono">' + esc(p.address) + '</div>'
    +   (leading && many ? '<span class="crown">Leading</span>' : '')
    + '</div>' + moodChip(p.mood) + '</div>'
    + '<div class="pstats">'
    +   '<div><div class="k">Score</div><div class="v num">'
    +     (p.score == null ? '--' : esc(p.score)) + '</div></div>'
    +   '<div><div class="k">Caught</div><div class="v num">' + esc(p.hits)
    +     '<small>of ' + esc(p.swings) + ' swings</small></div></div>'
    +   '<div><div class="k">Catch rate</div><div class="v num">'
    +     pct(p.catch_ratio) + '</div></div>'
    + '</div>'
    + '<div class="diff">'
    +   '<div class="dhead"><span class="k">Difficulty the AI chose</span>'
    +     '<span class="dband num" style="color:' + b.col + '">' + b.word
    +     '  ' + d.toFixed(2) + '</span></div>'
    +   '<div class="bar"><i style="width:' + pct(d) + ';background:' + b.col
    +     '"></i></div>'
    +   '<p class="note">' + note(p) + '</p>'
    + '</div></article>';
}

var EMPTY = '<div class="empty"><strong>Nobody is playing yet.</strong>'
  + 'Put on the Spectacles and start the Lens with <span class="mono">simulate'
  + '</span> unticked. Each pair that connects appears here as its own session '
  + 'with its own difficulty AI. Run a second client to see multiplayer.</div>';

function fmtUptime(s){
  s = Math.floor(s || 0);
  var m = Math.floor(s / 60);
  return m ? (m + 'm ' + (s % 60) + 's') : (s + 's');
}

async function tick(){
  try{
    const r = await fetch('/state', {cache:'no-store'});
    const s = await r.json();
    document.getElementById('status').textContent = 'live';
    document.getElementById('dot').classList.remove('off');

    var ps = (s.sessions || []).slice();
    // Highest score first, so the leaderboard reads top-left downwards.
    ps.sort(function(a, b){ return (b.score || 0) - (a.score || 0)
                                || a.id - b.id; });
    var many = ps.length > 1;
    document.getElementById('players').innerHTML = ps.length
      ? ps.map(function(p, i){ return playerCard(p, i === 0, many); }).join('')
      : EMPTY;

    document.getElementById('tuned').textContent   = ps.length;
    document.getElementById('preds').textContent   = s.predictions;
    document.getElementById('swings').textContent  = s.total_swings;
    document.getElementById('catches').textContent = s.total_hits;
    document.getElementById('eta').textContent =
      s.last_eta_ms ? s.last_eta_ms.toFixed(0) + ' ms' : '--';
    document.getElementById('conf').textContent =
      s.last_confidence ? s.last_confidence.toFixed(2) : '--';
    document.getElementById('up').textContent = fmtUptime(s.uptime_s);
  }catch(e){
    document.getElementById('status').textContent = 'offline';
    document.getElementById('dot').classList.add('off');
  }
}
tick(); setInterval(tick, 500);
</script></body></html>
"""


def _lan_address():
    '''
    Best effort at the address another device should use.

    The App runs in a container, so asking the socket layer "what is my
    address" returns the container's own bridge IP (172.x.x.x) rather than the
    board's address on your WiFi. That number is useless from a laptop, so
    detect it and say so rather than print a confident wrong answer.
    '''
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(('8.8.8.8', 80))      # no packets are actually sent
        addr = probe.getsockname()[0]
    except OSError:
        return None
    finally:
        probe.close()

    # Docker bridge ranges. 172.16-172.31 is the private block Docker uses.
    first, second = addr.split('.')[0], int(addr.split('.')[1])
    if first == '172' and 16 <= second <= 31:
        return None
    if addr.startswith('127.'):
        return None
    return addr


def start_dashboard(state_provider, port=DASHBOARD_PORT):
    '''
    Serve the dashboard on a background thread.

    state_provider() must return a dict shaped like:
        {sessions: [...], total_swings, total_hits, predictions,
         last_eta_ms, last_confidence, uptime_s}

    Each session should carry id, address, swings, hits, catch_ratio,
    difficulty and mood. score, target_ratio and dead_band are optional; the
    page falls back sensibly when they are missing.
    '''

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path.startswith('/state'):
                self._send(200, 'application/json',
                           json.dumps(state_provider()).encode())
            elif self.path in ('/', '/index.html'):
                self._send(200, 'text/html; charset=utf-8', PAGE.encode())
            else:
                self._send(404, 'text/plain', b'not found')

        def _send(self, code, ctype, body):
            try:
                self.send_response(code)
                self.send_header('Content-Type', ctype)
                self.send_header('Content-Length', str(len(body)))
                self.send_header('Cache-Control', 'no-store')
                self.end_headers()
                self.wfile.write(body)
            except (BrokenPipeError, ConnectionResetError):
                pass

        def log_message(self, fmt, *args):
            pass          # the App Lab console has better things to show

    def serve():
        try:
            HTTPServer(('0.0.0.0', port), Handler).serve_forever()
        except OSError as exc:
            print('Dashboard could not start on port %d: %s' % (port, exc))

    threading.Thread(target=serve, daemon=True).start()
    addr = _lan_address()
    if addr:
        print('Dashboard on http://%s:%d' % (addr, port))
    else:
        print('Dashboard listening on port %d.' % port)
        print('  Running in a container, so the board\'s WiFi address is not')
        print('  visible from here. Get it with  hostname -I  on the board,')
        print('  or from your phone hotspot\'s connected devices list.')

# ============ end of dashboard.py ============


WS_PORT = 8765
POLL_INTERVAL = 0.03          # seconds, ~30 Hz
MCU_SAMPLE_INTERVAL = 0.005   # the sketch samples at ~200 Hz
IDLE_PING_INTERVAL = 30.0     # how often to probe a silent player, seconds

clients = set()
bridge_lock = threading.Lock()

# ---- Multiplayer sessions -------------------------------------------------
# Every connected Lens is a session with its own adaptive difficulty model, so
# two players on the same net world each get tuned to their own skill rather
# than sharing one average. The dashboard reads this.
sessions = {}          # websocket -> Session
sessions_lock = threading.Lock()
next_session_id = 1
started_at = time.time()

stats = {
    "swings_detected": 0,     # swings the MCU reported
    "predictions": 0,         # forecasts the trajectory model emitted
    "last_eta_ms": 0.0,
    "last_confidence": 0.0,
}


class Session:
    """One connected player."""

    def __init__(self, sid, address):
        self.id = sid
        self.address = address
        self.dda = AdaptiveDifficulty()
        self.swings = 0
        self.hits = 0
        self.mood = "calm"
        self.score = 0          # the Lens is the authority on this

    def as_dict(self):
        return {
            "id": self.id,
            "address": self.address,
            "swings": self.swings,
            "hits": self.hits,
            "score": self.score,
            "catch_ratio": (self.hits / self.swings) if self.swings else 0.0,
            "difficulty": self.dda.level(),
            "mood": self.mood,
            # The dashboard explains in words why difficulty moved, so it needs
            # the model's real thresholds rather than a second copy of them.
            "target_ratio": self.dda.target_ratio,
            "dead_band": self.dda.dead_band,
        }


def dashboard_state():
    with sessions_lock:
        players = [s.as_dict() for s in sessions.values()]
    return {
        "sessions": sorted(players, key=lambda p: p["id"]),
        "total_swings": stats["swings_detected"],
        "total_hits": sum(p["hits"] for p in players),
        "predictions": stats["predictions"],
        "last_eta_ms": stats["last_eta_ms"],
        "last_confidence": stats["last_confidence"],
        "uptime_s": time.time() - started_at,
    }

# The trajectory model is shared: there is one net, so one motion stream.
# Difficulty is per player instead, and lives on each Session.
predictor = TrajectoryPredictor(horizon_ms=100.0)

# Monotonic clock for the reconstructed sample timestamps.
sample_clock = 0.0


WS_GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11'

HAPTIC_NAMES = {
    1: 'nearby',
    2: 'rare',
    3: 'capture',
    4: 'combo'
}

def build_handshake(request: str) -> str:
    '''Compute the Sec-WebSocket-Accept response for a client handshake.'''
    key = None
    for line in request.split('\r\n'):
        if line.lower().startswith('sec-websocket-key:'):
            key = line.split(':', 1)[1].strip()
            break
    if key is None:
        return None

    digest = hashlib.sha1((key + WS_GUID).encode()).digest()
    accept = base64.b64encode(digest).decode()
    return (
        'HTTP/1.1 101 Switching Protocols\r\n'
        'Upgrade: websocket\r\n'
        'Connection: Upgrade\r\n'
        'Sec-WebSocket-Accept: ' + accept + '\r\n\r\n'
    )


def encode_frame(payload: str) -> bytes:
    '''Encode a single unfragmented text frame. Server frames are never masked.'''
    data = payload.encode('utf-8')
    header = bytearray()
    header.append(0x81)  # FIN set, opcode 1 (text)

    length = len(data)
    if length < 126:
        header.append(length)
    elif length < (1 << 16):
        header.append(126)
        header.extend(struct.pack('>H', length))
    else:
        header.append(127)
        header.extend(struct.pack('>Q', length))

    return bytes(header) + data


def recv_exactly(conn: socket.socket, count: int) -> bytes:
    '''Read exactly count bytes, or return None if the peer went away.'''
    buf = b''
    while len(buf) < count:
        chunk = conn.recv(count - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def read_frame(conn: socket.socket):
    '''
    Read one frame. Returns (opcode, payload_bytes) or None on close.
    Client frames are always masked, so the mask is applied on the way in.
    '''
    head = recv_exactly(conn, 2)
    if head is None:
        return None

    opcode = head[0] & 0x0F
    masked = (head[1] & 0x80) != 0
    length = head[1] & 0x7F

    if length == 126:
        ext = recv_exactly(conn, 2)
        if ext is None:
            return None
        length = struct.unpack('>H', ext)[0]
    elif length == 127:
        ext = recv_exactly(conn, 8)
        if ext is None:
            return None
        length = struct.unpack('>Q', ext)[0]

    mask_key = b''
    if masked:
        mask_key = recv_exactly(conn, 4)
        if mask_key is None:
            return None

    payload = recv_exactly(conn, length) if length else b''
    if payload is None:
        return None

    if masked:
        payload = bytes(payload[i] ^ mask_key[i % 4] for i in range(len(payload)))

    return opcode, payload



def _send_text(conn, payload: str):
    data = payload.encode('utf-8')
    hdr = bytearray([0x81])
    n = len(data)
    if n < 126:
        hdr.append(n)
    elif n < (1 << 16):
        hdr.append(126)
        hdr.extend(struct.pack('>H', n))
    else:
        hdr.append(127)
        hdr.extend(struct.pack('>Q', n))
    conn.sendall(bytes(hdr) + data)


def handle_client(conn, addr):
    global next_session_id
    with sessions_lock:
        sid = next_session_id
        next_session_id += 1
        session = Session(sid, addr[0])
        sessions[conn] = session
    clients.add(conn)
    print(f"Player {sid} joined from {addr[0]}")

    try:
        request = conn.recv(4096).decode('utf-8', errors='ignore')
        response = build_handshake(request)
        if response is None:
            conn.close()
            return
        conn.sendall(response.encode())
        _send_text(conn, json.dumps(session.dda.params()))

        # Without this, a Lens that goes away without closing cleanly, which is
        # what happens every time the preview restarts, leaves this thread
        # blocked on recv forever and its session listed on the dashboard for
        # good. Rehearse a few times and the board invents a dozen players.
        conn.settimeout(IDLE_PING_INTERVAL)

        while True:
            try:
                frame = read_frame(conn)
            except socket.timeout:
                # The Lens only speaks when something happens, so a long
                # silence is normal and is never on its own grounds to drop a
                # player. Poke the socket instead: if the peer is gone its
                # machine answers with a reset, and the next read raises, which
                # ends this thread and clears the session below.
                conn.sendall(b'\x89\x00')      # ping, empty payload
                continue
            if frame is None:
                break
            opcode, payload = frame
            if opcode == 0x8:
                break
            if opcode == 0x9:
                conn.sendall(b'\x8a\x00')
                continue
            if opcode != 0x1:
                continue
            try:
                data = json.loads(payload.decode('utf-8'))
            except (ValueError, UnicodeDecodeError):
                continue

            kind = data.get("type")
            if kind == "haptic":
                pattern = int(data.get("pattern", 3))
                bridge_call("play_haptic", pattern)
                print(f"Player {sid}: haptic {pattern}")
            elif kind == "result":
                hit = bool(data.get("hit"))
                session.swings += 1
                if hit:
                    session.hits += 1
                if isinstance(data.get("mood"), str):
                    session.mood = data["mood"]
                if isinstance(data.get("score"), (int, float)):
                    session.score = int(data["score"])
                session.dda.record_result(hit)
                params = session.dda.params()
                print("Player %d %s | ratio %.2f | difficulty %.2f"
                      % (sid, "HIT " if hit else "miss",
                         params["catchRatio"], params["level"]))
                _send_text(conn, json.dumps(params))
    except (OSError, ConnectionResetError, BrokenPipeError):
        pass
    finally:
        clients.discard(conn)
        with sessions_lock:
            sessions.pop(conn, None)
        try:
            conn.close()
        except OSError:
            pass
        print(f"Player {sid} left")


def _accept_loop(server):
    while True:
        try:
            conn, addr = server.accept()
        except OSError:
            return
        threading.Thread(target=handle_client, args=(conn, addr),
                         daemon=True).start()


def start_ws_server():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(("0.0.0.0", WS_PORT))
    server.listen(8)
    print(f"WebSocket server listening on port {WS_PORT}")
    threading.Thread(target=_accept_loop, args=(server,), daemon=True).start()


start_ws_server()
start_dashboard(dashboard_state)


def broadcast(obj):
    msg = json.dumps(obj)
    for conn in list(clients):
        try:
            _send_text(conn, msg)
        except OSError:
            pass


def parse_samples(raw):
    '''
    The sketch hands back the magnitudes captured since the last call, as a
    comma separated string such as "1.02,1.15,1.44". Returns a list of floats,
    empty if there was nothing or the payload was malformed.
    '''
    if not raw:
        return []
    out = []
    for piece in str(raw).split(","):
        piece = piece.strip()
        if not piece:
            continue
        try:
            out.append(float(piece))
        except ValueError:
            continue
    return out


bridge_errors = 0


def bridge_call(name, *args):
    '''
    Call the MCU, and never let a failure escape. An exception raised out of
    the user loop can take the whole Linux side down, which mid-take means
    the net simply stops existing. A dropped poll is recoverable; a dead
    process is not.
    '''
    global bridge_errors
    try:
        with bridge_lock:
            result = Bridge.call(name, *args)
        bridge_errors = 0
        return result
    except Exception as exc:                      # noqa: BLE001
        bridge_errors += 1
        # Only complain occasionally, or a persistent fault floods the console
        # and hides everything else.
        if bridge_errors == 1 or bridge_errors % 100 == 0:
            print("Bridge call %s failed (%d in a row): %s"
                  % (name, bridge_errors, exc))
        return None


def loop():
    global sample_clock

    # ---- 1. Drain the IMU sample buffer and run the predictor ----
    raw = bridge_call("get_samples")

    for mag in parse_samples(raw):
        sample_clock += MCU_SAMPLE_INTERVAL
        prediction = predictor.update(sample_clock, mag)
        if prediction:
            stats["predictions"] += 1
            stats["last_eta_ms"] = prediction.eta_ms
            stats["last_confidence"] = prediction.confidence
            print("Predicted swing peak in %.0f ms (confidence %.2f)"
                  % (prediction.eta_ms, prediction.confidence))
            msg = {"type": "predict"}
            msg.update(prediction.as_dict())
            broadcast(msg)

    # ---- 2. Confirmed swings still come from the MCU's own detector ----
    peak = bridge_call("get_event")
    if peak and peak > 0:
        stats["swings_detected"] += 1
        print(f"Swing detected, peak {peak:.2f} g")
        broadcast({"type": "swing", "peak": round(float(peak), 2)})

    time.sleep(POLL_INTERVAL)


App.run(user_loop=loop)
