# Neon-Net - Linux side, SINGLE FILE, NO DEPENDENCIES
# ----------------------------------------------------
# GENERATED by build-standalone.py. Do not edit directly: edit main-nodeps.py,
# neon_ai.py or dashboard.py and regenerate, or your change will be lost.
#
# Paste this whole file over the App's main.py. Nothing to install, no second
# file needed. It contains:
#   - the two AI models (trajectory prediction, adaptive difficulty)
#   - the App Lab game dashboard on port 8080
#   - a WebSocket server on port 8765, raw sockets, no packages
#   - per player multiplayer sessions
#   - the Bridge polling loop for the MCU

# Neon-Net - Linux side, NO DEPENDENCIES build
# ---------------------------------------------
# Identical behaviour to main.py, but the WebSocket server is raw sockets from
# the standard library instead of the `websockets` package. Use this when
# App Lab will not install dependencies into the app container.
#
# The frame layer here is the same code proven end to end in mock-net.py:
# handshake, masked inbound frames, unmasked outbound frames.
#
# Nothing to install. Nothing to fail on the day.

import json
import threading
import time
import socket
import struct
import base64
import hashlib

from arduino.app_utils import *

# ============ neon_ai.py, inlined ============

from collections import deque

# ---------------------------------------------------------------- prediction

DEFAULT_HORIZON_MS = 100.0


class Prediction:
    '''A forecast that a swing will peak shortly.'''

    def __init__(self, eta_ms, predicted_peak, confidence):
        self.eta_ms = eta_ms
        self.predicted_peak = predicted_peak
        self.confidence = confidence

    def as_dict(self):
        return {
            'etaMs': round(self.eta_ms, 1),
            'predictedPeak': round(self.predicted_peak, 2),
            'confidence': round(self.confidence, 2)
        }

    def __repr__(self):
        return ('Prediction(eta_ms=%.1f, peak=%.2f, conf=%.2f)'
                % (self.eta_ms, self.predicted_peak, self.confidence))


class TrajectoryPredictor:
    '''
    Watches acceleration magnitude and extrapolates forward to find the peak.

    The model fits a parabola through three smoothed points and solves for its
    vertex, which is the peak of the swing. If that vertex lands inside the
    horizon, the swing is announced early along with the peak value it is
    heading for.

    A parabola rather than plain Newtonian extrapolation on purpose: a swing
    decelerates harder the closer it gets to its peak, so projecting the
    current slope forward at constant acceleration lands the peak roughly twice
    as far ahead as it really is. Fitting the curve through three points picks
    the turning point up directly.

    One prediction per swing. It re-arms once the motion has died back down,
    so a single swing cannot fire a burst of forecasts.
    '''

    # Calibrated against the net as actually built, not a bare breadboard.
    # Mounting the electronics on a handle tripled the walking figure:
    #
    #                  bare board      mounted on the net
    #   walking        0.65 to 1.08    2.0 to 3.0
    #   a real swing   peaks at 5.5    above 4.0
    #
    # The old arm threshold of 1.6 g sat well below walking, so the predictor
    # armed on every footfall. 3.4 clears both steady walking and a brisk
    # jostling carry, which peaks nearer 3.2. Re-arm at 2.4 so it resets
    # between swings without needing the net to come fully to rest.
    #
    # NOTE: measured WITHOUT the power bank fitted. Adding that mass will move
    # the walking figure again, so re-measure once the net is complete.
    def __init__(self,
                 horizon_ms=DEFAULT_HORIZON_MS,
                 arm_threshold_g=3.4,
                 rearm_threshold_g=2.4,
                 min_slope=8.0,
                 smoothing=3):
        self.horizon_ms = float(horizon_ms)
        self.arm_threshold_g = float(arm_threshold_g)
        self.rearm_threshold_g = float(rearm_threshold_g)
        self.min_slope = float(min_slope)
        self.smoothing = max(1, int(smoothing))

        self._samples = deque(maxlen=16)   # (t_seconds, magnitude_g)
        self._armed = True
        self.last_prediction = None

    def reset(self):
        self._samples.clear()
        self._armed = True
        self.last_prediction = None

    def _smoothed(self, index_from_end):
        '''Mean of the last `smoothing` samples ending at the given offset.'''
        end = len(self._samples) - index_from_end
        start = max(0, end - self.smoothing)
        window = list(self._samples)[start:end]
        if not window:
            return None
        t = sum(s[0] for s in window) / len(window)
        mag = sum(s[1] for s in window) / len(window)
        return t, mag

    def update(self, t_seconds, magnitude_g):
        '''
        Feed one IMU sample. Returns a Prediction the moment a peak is
        forecast inside the horizon, otherwise None.
        '''
        self._samples.append((float(t_seconds), float(magnitude_g)))

        # Re-arm once the net has settled, ready for the next swing.
        if not self._armed and magnitude_g < self.rearm_threshold_g:
            self._armed = True
            return None

        if not self._armed:
            return None
        if magnitude_g < self.arm_threshold_g:
            return None
        if len(self._samples) < self.smoothing * 3:
            return None

        # Three smoothed points, evenly spaced back through the buffer.
        p2 = self._smoothed(0)
        p1 = self._smoothed(self.smoothing)
        p0 = self._smoothed(self.smoothing * 2)
        if p0 is None or p1 is None or p2 is None:
            return None

        t0, m0 = p0
        t1, m1 = p1
        t2, m2 = p2

        dt1 = t2 - t1
        dt0 = t1 - t0
        if dt1 <= 1e-6 or dt0 <= 1e-6:
            return None

        # Divided differences give the parabola through the three points.
        f01 = (m1 - m0) / dt0
        f12 = (m2 - m1) / dt1
        curvature = (f12 - f01) / (t2 - t0)      # the quadratic coefficient

        # Must be rising, and curving over. That combination has a peak ahead.
        v_now = f12
        if v_now <= self.min_slope or curvature >= -1e-9:
            return None

        # Vertex of the parabola, in Newton form.
        t_peak = 0.5 * (t0 + t1) - f01 / (2.0 * curvature)

        eta_s = t_peak - t2
        eta_ms = eta_s * 1000.0
        if eta_ms <= 0 or eta_ms > self.horizon_ms:
            return None

        predicted_peak = (m0
                          + f01 * (t_peak - t0)
                          + curvature * (t_peak - t0) * (t_peak - t1))

        # Confidence falls off as the forecast reaches further ahead, and rises
        # with how decisively the swing is accelerating.
        reach = 1.0 - (eta_ms / self.horizon_ms)
        vigour = min(1.0, v_now / (self.min_slope * 4.0))
        confidence = max(0.0, min(1.0, 0.45 * reach + 0.55 * vigour))

        self._armed = False
        self.last_prediction = Prediction(eta_ms, predicted_peak, confidence)
        return self.last_prediction


# ---------------------------------------------------------------- difficulty

class AdaptiveDifficulty:
    '''
    Keeps the player near a target catch rate.

    Every swing produces a hit or a miss. Over a sliding window the ratio is
    compared against target_ratio, and a single difficulty value between 0 and
    1 moves to close the gap. Too easy and it climbs, too hard and it drops.

    The Lens receives derived parameters rather than the raw number, so all the
    balancing lives here on the board and the Lens simply obeys.
    '''

    def __init__(self,
                 window=10,
                 target_ratio=0.55,
                 dead_band=0.12,
                 step=0.1,
                 start=0.35,
                 min_samples=4):
        self.window = int(window)
        self.target_ratio = float(target_ratio)
        self.dead_band = float(dead_band)
        self.step = float(step)
        self.min_samples = int(min_samples)

        self._outcomes = deque(maxlen=self.window)
        self._difficulty = max(0.0, min(1.0, float(start)))
        self.swings = 0
        self.hits = 0

    # -- inputs --

    def record_result(self, hit):
        '''Record the outcome of one swing, then re-balance.'''
        self._outcomes.append(bool(hit))
        self.swings += 1
        if hit:
            self.hits += 1
        self._rebalance()

    def _rebalance(self):
        if len(self._outcomes) < self.min_samples:
            return
        ratio = self.catch_ratio()
        if ratio > self.target_ratio + self.dead_band:
            self._difficulty = min(1.0, self._difficulty + self.step)
        elif ratio < self.target_ratio - self.dead_band:
            self._difficulty = max(0.0, self._difficulty - self.step)

    # -- outputs --

    def catch_ratio(self):
        if not self._outcomes:
            return 0.0
        return sum(1 for o in self._outcomes if o) / float(len(self._outcomes))

    def level(self):
        return self._difficulty

    def params(self):
        '''
        The message the Lens acts on. Everything is a multiplier so the Lens
        keeps its own tuned baselines and simply scales them.
        '''
        d = self._difficulty
        return {
            'type': 'difficulty',
            'level': round(d, 3),
            'catchRatio': round(self.catch_ratio(), 3),
            'speedMult': round(1.0 + d * 0.8, 3),      # drift and flee speed
            'evasionMult': round(1.0 + d * 1.2, 3),    # how far they dodge
            'alertMult': round(1.0 + d * 0.9, 3),      # how early they notice
            'cloaking': d > 0.65,                      # rare ones fade out
            'skittishBias': round(min(0.8, 0.35 + d * 0.45), 3)
        }

# ============ end of neon_ai.py ============

# ============ dashboard.py, inlined ============

import json
import socket
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer

DASHBOARD_PORT = 8080

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Neon-Net Control</title>
<style>
 :root{
   --bg:#070d12;--panel:#0e1922;--line:#1b2a36;--ink:#dff2f6;--dim:#6d8794;
   --cyan:#26f0ff;--violet:#7a80ff;--gold:#ffc93c;
 }
 *{box-sizing:border-box}
 body{margin:0;background:var(--bg);color:var(--ink);
   font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace;
   font-size:15px;line-height:1.5}
 .wrap{max-width:1000px;margin:0 auto;padding:28px 18px 60px;
   display:flex;flex-direction:column;gap:24px}
 header{display:flex;justify-content:space-between;align-items:baseline;
   flex-wrap:wrap;gap:10px;border-bottom:1px solid var(--line);padding-bottom:14px}
 h1{margin:0;font-size:20px;letter-spacing:.14em;text-transform:uppercase}
 .live{font-size:12px;color:var(--dim);display:flex;align-items:center;gap:8px}
 .dot{width:8px;height:8px;border-radius:50%;background:var(--cyan);
   box-shadow:0 0 10px var(--cyan);animation:p 1.6s infinite}
 .dot.off{background:#54646f;box-shadow:none}
 @keyframes p{0%,100%{opacity:1}50%{opacity:.25}}
 @media (prefers-reduced-motion:reduce){.dot{animation:none}}
 .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}
 .card{background:var(--panel);border:1px solid var(--line);border-radius:4px;padding:16px}
 .k{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--dim)}
 .v{font-size:30px;margin-top:6px;font-variant-numeric:tabular-nums}
 h2{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--dim);
   margin:0 0 10px;font-weight:400}
 table{width:100%;border-collapse:collapse;font-size:14px}
 th,td{text-align:left;padding:9px 10px;border-bottom:1px solid var(--line)}
 th{font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--dim);font-weight:400}
 td.n{text-align:right;font-variant-numeric:tabular-nums}
 .bar{height:6px;background:#122029;border-radius:3px;overflow:hidden;margin-top:8px}
 .bar i{display:block;height:100%;background:var(--cyan);transition:width .4s}
 .tag{font-size:11px;padding:2px 7px;border:1px solid currentColor;border-radius:2px}
 .calm{color:var(--cyan)}.curious{color:var(--violet)}.spooked{color:var(--gold)}
 .empty{color:var(--dim);padding:18px 10px}
 .wrapover{overflow-x:auto}
</style></head><body>
<div class="wrap">
 <header>
   <h1>Neon-Net Control</h1>
   <div class="live"><span class="dot" id="dot"></span><span id="status">connecting</span></div>
 </header>

 <div class="grid">
   <div class="card"><div class="k">Sessions</div><div class="v" id="sessions">0</div></div>
   <div class="card"><div class="k">Swings</div><div class="v" id="swings">0</div></div>
   <div class="card"><div class="k">Catches</div><div class="v" id="catches">0</div></div>
   <div class="card"><div class="k">Predictions</div><div class="v" id="preds">0</div></div>
 </div>

 <div class="card">
   <h2>Players</h2>
   <div class="wrapover">
   <table><thead><tr>
     <th>Session</th><th>Address</th><th class="n">Swings</th>
     <th class="n">Catches</th><th class="n">Catch rate</th><th>Difficulty</th>
   </tr></thead><tbody id="rows"></tbody></table>
   </div>
 </div>

 <div class="card">
   <h2>Kinetic engine</h2>
   <div class="grid">
     <div><div class="k">Last predicted lead</div><div class="v" id="eta">--</div></div>
     <div><div class="k">Confidence</div><div class="v" id="conf">--</div></div>
     <div><div class="k">Uptime</div><div class="v" id="up">--</div></div>
   </div>
 </div>
</div>
<script>
function pct(x){return (x*100).toFixed(0)+'%';}
async function tick(){
  try{
    const r = await fetch('/state',{cache:'no-store'});
    const s = await r.json();
    document.getElementById('status').textContent='live';
    document.getElementById('dot').classList.remove('off');
    document.getElementById('sessions').textContent=s.sessions.length;
    document.getElementById('swings').textContent=s.total_swings;
    document.getElementById('catches').textContent=s.total_hits;
    document.getElementById('preds').textContent=s.predictions;
    document.getElementById('eta').textContent=s.last_eta_ms?s.last_eta_ms.toFixed(0)+' ms':'--';
    document.getElementById('conf').textContent=s.last_confidence?s.last_confidence.toFixed(2):'--';
    document.getElementById('up').textContent=Math.floor(s.uptime_s)+' s';
    const rows=document.getElementById('rows');
    if(!s.sessions.length){
      rows.innerHTML='<tr><td colspan="6" class="empty">No players connected. Start the Lens with simulate unticked.</td></tr>';
    }else{
      rows.innerHTML=s.sessions.map(p=>`<tr>
        <td>#${p.id} <span class="tag ${p.mood}">${p.mood}</span></td>
        <td>${p.address}</td>
        <td class="n">${p.swings}</td>
        <td class="n">${p.hits}</td>
        <td class="n">${pct(p.catch_ratio)}</td>
        <td>${p.difficulty.toFixed(2)}<div class="bar"><i style="width:${pct(p.difficulty)}"></i></div></td>
      </tr>`).join('');
    }
  }catch(e){
    document.getElementById('status').textContent='offline';
    document.getElementById('dot').classList.add('off');
  }
}
tick(); setInterval(tick, 500);
</script></body></html>
"""


def _lan_address():
    '''
    Best effort at the address another device should use.

    The App runs in a container, so asking the socket layer "what is my
    address" returns the container's own bridge IP (172.x.x.x) rather than the
    board's address on your WiFi. That number is useless from a laptop, so
    detect it and say so rather than print a confident wrong answer.
    '''
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(('8.8.8.8', 80))      # no packets are actually sent
        addr = probe.getsockname()[0]
    except OSError:
        return None
    finally:
        probe.close()

    # Docker bridge ranges. 172.16-172.31 is the private block Docker uses.
    first, second = addr.split('.')[0], int(addr.split('.')[1])
    if first == '172' and 16 <= second <= 31:
        return None
    if addr.startswith('127.'):
        return None
    return addr


def start_dashboard(state_provider, port=DASHBOARD_PORT):
    '''
    Serve the dashboard on a background thread.

    state_provider() must return a dict shaped like:
        {sessions: [...], total_swings, total_hits, predictions,
         last_eta_ms, last_confidence, uptime_s}
    '''

    class Handler(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path.startswith('/state'):
                self._send(200, 'application/json',
                           json.dumps(state_provider()).encode())
            elif self.path in ('/', '/index.html'):
                self._send(200, 'text/html; charset=utf-8', PAGE.encode())
            else:
                self._send(404, 'text/plain', b'not found')

        def _send(self, code, ctype, body):
            try:
                self.send_response(code)
                self.send_header('Content-Type', ctype)
                self.send_header('Content-Length', str(len(body)))
                self.send_header('Cache-Control', 'no-store')
                self.end_headers()
                self.wfile.write(body)
            except (BrokenPipeError, ConnectionResetError):
                pass

        def log_message(self, fmt, *args):
            pass          # the App Lab console has better things to show

    def serve():
        try:
            HTTPServer(('0.0.0.0', port), Handler).serve_forever()
        except OSError as exc:
            print('Dashboard could not start on port %d: %s' % (port, exc))

    threading.Thread(target=serve, daemon=True).start()
    addr = _lan_address()
    if addr:
        print('Dashboard on http://%s:%d' % (addr, port))
    else:
        print('Dashboard listening on port %d.' % port)
        print('  Running in a container, so the board\'s WiFi address is not')
        print('  visible from here. Get it with  hostname -I  on the board,')
        print('  or from your phone hotspot\'s connected devices list.')

# ============ end of dashboard.py ============


WS_PORT = 8765
POLL_INTERVAL = 0.03          # seconds, ~30 Hz
MCU_SAMPLE_INTERVAL = 0.005   # the sketch samples at ~200 Hz

clients = set()
bridge_lock = threading.Lock()

# ---- Multiplayer sessions -------------------------------------------------
# Every connected Lens is a session with its own adaptive difficulty model, so
# two players on the same net world each get tuned to their own skill rather
# than sharing one average. The dashboard reads this.
sessions = {}          # websocket -> Session
sessions_lock = threading.Lock()
next_session_id = 1
started_at = time.time()

stats = {
    "swings_detected": 0,     # swings the MCU reported
    "predictions": 0,         # forecasts the trajectory model emitted
    "last_eta_ms": 0.0,
    "last_confidence": 0.0,
}


class Session:
    """One connected player."""

    def __init__(self, sid, address):
        self.id = sid
        self.address = address
        self.dda = AdaptiveDifficulty()
        self.swings = 0
        self.hits = 0
        self.mood = "calm"

    def as_dict(self):
        return {
            "id": self.id,
            "address": self.address,
            "swings": self.swings,
            "hits": self.hits,
            "catch_ratio": (self.hits / self.swings) if self.swings else 0.0,
            "difficulty": self.dda.level(),
            "mood": self.mood,
        }


def dashboard_state():
    with sessions_lock:
        players = [s.as_dict() for s in sessions.values()]
    return {
        "sessions": sorted(players, key=lambda p: p["id"]),
        "total_swings": stats["swings_detected"],
        "total_hits": sum(p["hits"] for p in players),
        "predictions": stats["predictions"],
        "last_eta_ms": stats["last_eta_ms"],
        "last_confidence": stats["last_confidence"],
        "uptime_s": time.time() - started_at,
    }

# The trajectory model is shared: there is one net, so one motion stream.
# Difficulty is per player instead, and lives on each Session.
predictor = TrajectoryPredictor(horizon_ms=100.0)

# Monotonic clock for the reconstructed sample timestamps.
sample_clock = 0.0


WS_GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11'

HAPTIC_NAMES = {
    1: 'nearby',
    2: 'rare',
    3: 'capture',
    4: 'combo'
}

def build_handshake(request: str) -> str:
    '''Compute the Sec-WebSocket-Accept response for a client handshake.'''
    key = None
    for line in request.split('\r\n'):
        if line.lower().startswith('sec-websocket-key:'):
            key = line.split(':', 1)[1].strip()
            break
    if key is None:
        return None

    digest = hashlib.sha1((key + WS_GUID).encode()).digest()
    accept = base64.b64encode(digest).decode()
    return (
        'HTTP/1.1 101 Switching Protocols\r\n'
        'Upgrade: websocket\r\n'
        'Connection: Upgrade\r\n'
        'Sec-WebSocket-Accept: ' + accept + '\r\n\r\n'
    )


def encode_frame(payload: str) -> bytes:
    '''Encode a single unfragmented text frame. Server frames are never masked.'''
    data = payload.encode('utf-8')
    header = bytearray()
    header.append(0x81)  # FIN set, opcode 1 (text)

    length = len(data)
    if length < 126:
        header.append(length)
    elif length < (1 << 16):
        header.append(126)
        header.extend(struct.pack('>H', length))
    else:
        header.append(127)
        header.extend(struct.pack('>Q', length))

    return bytes(header) + data


def recv_exactly(conn: socket.socket, count: int) -> bytes:
    '''Read exactly count bytes, or return None if the peer went away.'''
    buf = b''
    while len(buf) < count:
        chunk = conn.recv(count - len(buf))
        if not chunk:
            return None
        buf += chunk
    return buf


def read_frame(conn: socket.socket):
    '''
    Read one frame. Returns (opcode, payload_bytes) or None on close.
    Client frames are always masked, so the mask is applied on the way in.
    '''
    head = recv_exactly(conn, 2)
    if head is None:
        return None

    opcode = head[0] & 0x0F
    masked = (head[1] & 0x80) != 0
    length = head[1] & 0x7F

    if length == 126:
        ext = recv_exactly(conn, 2)
        if ext is None:
            return None
        length = struct.unpack('>H', ext)[0]
    elif length == 127:
        ext = recv_exactly(conn, 8)
        if ext is None:
            return None
        length = struct.unpack('>Q', ext)[0]

    mask_key = b''
    if masked:
        mask_key = recv_exactly(conn, 4)
        if mask_key is None:
            return None

    payload = recv_exactly(conn, length) if length else b''
    if payload is None:
        return None

    if masked:
        payload = bytes(payload[i] ^ mask_key[i % 4] for i in range(len(payload)))

    return opcode, payload



def _send_text(conn, payload: str):
    data = payload.encode('utf-8')
    hdr = bytearray([0x81])
    n = len(data)
    if n < 126:
        hdr.append(n)
    elif n < (1 << 16):
        hdr.append(126)
        hdr.extend(struct.pack('>H', n))
    else:
        hdr.append(127)
        hdr.extend(struct.pack('>Q', n))
    conn.sendall(bytes(hdr) + data)


def handle_client(conn, addr):
    global next_session_id
    with sessions_lock:
        sid = next_session_id
        next_session_id += 1
        session = Session(sid, addr[0])
        sessions[conn] = session
    clients.add(conn)
    print(f"Player {sid} joined from {addr[0]}")

    try:
        request = conn.recv(4096).decode('utf-8', errors='ignore')
        response = build_handshake(request)
        if response is None:
            conn.close()
            return
        conn.sendall(response.encode())
        _send_text(conn, json.dumps(session.dda.params()))

        while True:
            frame = read_frame(conn)
            if frame is None:
                break
            opcode, payload = frame
            if opcode == 0x8:
                break
            if opcode == 0x9:
                conn.sendall(b'\x8a\x00')
                continue
            if opcode != 0x1:
                continue
            try:
                data = json.loads(payload.decode('utf-8'))
            except (ValueError, UnicodeDecodeError):
                continue

            kind = data.get("type")
            if kind == "haptic":
                pattern = int(data.get("pattern", 3))
                bridge_call("play_haptic", pattern)
                print(f"Player {sid}: haptic {pattern}")
            elif kind == "result":
                hit = bool(data.get("hit"))
                session.swings += 1
                if hit:
                    session.hits += 1
                if isinstance(data.get("mood"), str):
                    session.mood = data["mood"]
                session.dda.record_result(hit)
                params = session.dda.params()
                print("Player %d %s | ratio %.2f | difficulty %.2f"
                      % (sid, "HIT " if hit else "miss",
                         params["catchRatio"], params["level"]))
                _send_text(conn, json.dumps(params))
    except (OSError, ConnectionResetError, BrokenPipeError):
        pass
    finally:
        clients.discard(conn)
        with sessions_lock:
            sessions.pop(conn, None)
        try:
            conn.close()
        except OSError:
            pass
        print(f"Player {sid} left")


def _accept_loop(server):
    while True:
        try:
            conn, addr = server.accept()
        except OSError:
            return
        threading.Thread(target=handle_client, args=(conn, addr),
                         daemon=True).start()


def start_ws_server():
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(("0.0.0.0", WS_PORT))
    server.listen(8)
    print(f"WebSocket server listening on port {WS_PORT}")
    threading.Thread(target=_accept_loop, args=(server,), daemon=True).start()


start_ws_server()
start_dashboard(dashboard_state)


def broadcast(obj):
    msg = json.dumps(obj)
    for conn in list(clients):
        try:
            _send_text(conn, msg)
        except OSError:
            pass


def parse_samples(raw):
    '''
    The sketch hands back the magnitudes captured since the last call, as a
    comma separated string such as "1.02,1.15,1.44". Returns a list of floats,
    empty if there was nothing or the payload was malformed.
    '''
    if not raw:
        return []
    out = []
    for piece in str(raw).split(","):
        piece = piece.strip()
        if not piece:
            continue
        try:
            out.append(float(piece))
        except ValueError:
            continue
    return out


bridge_errors = 0


def bridge_call(name, *args):
    '''
    Call the MCU, and never let a failure escape. An exception raised out of
    the user loop can take the whole Linux side down, which mid-take means
    the net simply stops existing. A dropped poll is recoverable; a dead
    process is not.
    '''
    global bridge_errors
    try:
        with bridge_lock:
            result = Bridge.call(name, *args)
        bridge_errors = 0
        return result
    except Exception as exc:                      # noqa: BLE001
        bridge_errors += 1
        # Only complain occasionally, or a persistent fault floods the console
        # and hides everything else.
        if bridge_errors == 1 or bridge_errors % 100 == 0:
            print("Bridge call %s failed (%d in a row): %s"
                  % (name, bridge_errors, exc))
        return None


def loop():
    global sample_clock

    # ---- 1. Drain the IMU sample buffer and run the predictor ----
    raw = bridge_call("get_samples")

    for mag in parse_samples(raw):
        sample_clock += MCU_SAMPLE_INTERVAL
        prediction = predictor.update(sample_clock, mag)
        if prediction:
            stats["predictions"] += 1
            stats["last_eta_ms"] = prediction.eta_ms
            stats["last_confidence"] = prediction.confidence
            print("Predicted swing peak in %.0f ms (confidence %.2f)"
                  % (prediction.eta_ms, prediction.confidence))
            msg = {"type": "predict"}
            msg.update(prediction.as_dict())
            broadcast(msg)

    # ---- 2. Confirmed swings still come from the MCU's own detector ----
    peak = bridge_call("get_event")
    if peak and peak > 0:
        stats["swings_detected"] += 1
        print(f"Swing detected, peak {peak:.2f} g")
        broadcast({"type": "swing", "peak": round(float(peak), 2)})

    time.sleep(POLL_INTERVAL)


App.run(user_loop=loop)
